### ISSUE TITLE
Unknown state

### ISSUE THREAD

**Issue by dankarization** [jethome-hassio-addons/addon-jethub-mqtt-io#46]
Every time after restart all sensors stay unknown until the real state they are in right now changes to something different. If state changed during the reboot, there's no way to know about that. Can you make manual sensors poll 1 time after addon start to load their current state?
![image](https://user-images.githubusercontent.com/26330178/229029623-39caba8a-f777-4223-abc5-441ba5c4ad95.png)

**Comment by hacker-cb** [comment]
Actually addon is just wrapper for https://github.com/flyte/mqtt-io.  So we can’t make manual polling.
